services:
  - type: web
    name: simple-chat
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
